// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgJYZXl5h1_mZt-phX0RBdvztUnBX6J84',
    appId: '1:164624751065:web:001025d501b79e0f0761c8',
    messagingSenderId: '164624751065',
    projectId: 'ai-helmet-2186c',
    authDomain: 'ai-helmet-2186c.firebaseapp.com',
    storageBucket: 'ai-helmet-2186c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtafvhIWT1fU8_Sa0cOLCLEWoa-YmHsH8',
    appId: '1:164624751065:android:a2b6694ff8d1f0210761c8',
    messagingSenderId: '164624751065',
    projectId: 'ai-helmet-2186c',
    storageBucket: 'ai-helmet-2186c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNj1MocMm7SaTLLDr58IiyvTC4-_vlF2g',
    appId: '1:164624751065:ios:3175e53403d76fa50761c8',
    messagingSenderId: '164624751065',
    projectId: 'ai-helmet-2186c',
    storageBucket: 'ai-helmet-2186c.firebasestorage.app',
    iosBundleId: 'com.example.isd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNj1MocMm7SaTLLDr58IiyvTC4-_vlF2g',
    appId: '1:164624751065:ios:3175e53403d76fa50761c8',
    messagingSenderId: '164624751065',
    projectId: 'ai-helmet-2186c',
    storageBucket: 'ai-helmet-2186c.firebasestorage.app',
    iosBundleId: 'com.example.isd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgJYZXl5h1_mZt-phX0RBdvztUnBX6J84',
    appId: '1:164624751065:web:cb8641ba915744180761c8',
    messagingSenderId: '164624751065',
    projectId: 'ai-helmet-2186c',
    authDomain: 'ai-helmet-2186c.firebaseapp.com',
    storageBucket: 'ai-helmet-2186c.firebasestorage.app',
  );
}
